### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by VycktorStark**
Everything is OK

### CODE REVIEW

**Comment by xVir** [comment]
Hi, @VycktorStark 
This pull request is empty. Is it right?

Thanks!

**Comment by VycktorStark** [comment]
Please read the correction and test it, it is working normally!

**Comment by xVir** [comment]
Hi, @VycktorStark 
Thanks!
But it seems your second commit fully discards the previous commit, and so still there is no changes in this pull request.

screen 2016-12-14 15 13 55

So, it seems, you have to return some of your original changes...

Thanks!

**Comment by sstepashka** [comment]
Did you add new feature? Did you fix some bug? What real useful in this pull request? Reformatting code?

**Pull request closed without merging**
